title: Osman Baskaya blog
email: 
description: "Logger"
baseurl: ""
url: "http://osmanbaskaya.github.io"
twitter_username: osmanbaskaya
github_username:  osmanbaskaya

# Build settings
markdown: redcarpet
permalink: pretty

